name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build Addition Tests (64)
        run: yarn run build:add.64
      
      - name: Build Subtraction Tests (64)
        run: yarn run build:sub.64
      
      - name: Build Multiplication Tests (64)
        run: yarn run build:mult.64

      - name: Build Division Tests (64)
        run: yarn run build:div.64

      - name: Build Logarithm Tests (64)
        run: yarn run build:log.64


      - name: Run Addition Tests (64)
        run: yarn run test --suite add.64

      - name: Run Subtraction Tests (64)
        run: yarn run test --suite sub.64

      - name: Run Multiplication Tests (64)
        run: yarn run test --suite mult.64

      - name: Run Division Tests (64)
        run: yarn run test --suite div.64

      - name: Run Logarithm Tests (64)
        run: yarn run test --suite log.64


      - name: Build Addition Tests (128)
        run: yarn run build:add.128
      
      - name: Build Subtraction Tests (128)
        run: yarn run build:sub.128

      - name: Run Multiplication Tests (128)
        run: yarn run test --suite mult.128

      - name: Run Division Tests (128)
        run: yarn run test --suite div.128

      - name: Run Addition Tests (128)
        run: yarn run test --suite add.128

      - name: Run Subtraction Tests (128)
        run: yarn run test --suite sub.128

      - name: Run Multiplication Tests (128)
        run: yarn run test --suite mult.128
